
class ILOCConstants(object):

    ADD              = "add"
    ADDI             = "addi"
    AND              = "and"
    CALL             = "call"
    CBREQ            = "cbreq"
    CBRGE            = "cbrge"
    CBRGT            = "cbrgt"
    CBRLE            = "cbrle"
    CBRLT            = "cbrlt"
    CBRNE            = "cbrne"
    COMP             = "comp"
    COMPI            = "compi"
    DEL              = "del"
    DIV              = "div"
    EMPTY            = "$"
    JUMPI            = "jumpi"
    LABEL            = "label"
    LDSW             = "ldsw"
    LOADAI           = "loadai"
    LOADGLOBAL       = "loadglobal"
    LOADI            = "loadi"
    LOADINARGUMENT   = "loadinargument"
    LOADRET          = "loadret"
    MOV              = "mov"
    MULT             = "mult"
    MULTI            = "multi"
    NEW              = "new"
    OR               = "or"
    PRINT            = "print"
    PRINTLN          = "println"
    READ             = "read"
    RET              = "ret"
    STOREAI          = "storeai"
    STOREGLOBAL      = "storeglobal"
    STOREINARGUMENT  = "storeinargument"
    STOREOUTARGUMENT = "storeoutargument"
    STORERET         = "storeret"
    SUB              = "sub"
    XORI             = "xori"

    GLOBAL        = "global"
    LOCAL         = "local"
    STRUCT_MEMBER = "struct member"
    ARGUMENT      = "argument"
    MEMORY        = "memory"
